apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: webserverstacks.example.org
spec:
  group: example.org
  names:
    kind: WebServerStack
    plural: webserverstacks
    singular: webserverstack
  claimNames:
    kind: WebServerStackClaim
    plural: webserverstackclaims
    singular: webserverstackclaim
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                account:
                  type: string
                bucketName:
                  type: string
                fileName:
                  type: string
      additionalPrinterColumns:
        - name: SYNCED
          type: string
          description: "The sync status of this resource."
          jsonPath: ".status.conditions[?(@.type=='Synced')].status"
        - name: READY
          type: string
          description: "The readiness status of this resource."
          jsonPath: ".status.conditions[?(@.type=='Ready')].status"
  defaultCompositionRef:
    name: webserverstack-composition
