apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-shell
  labels:
    app: {{ .Chart.Name }}
spec:
  serviceAccountName: pod-role
  containers:
  - name: {{ .Values.containerName }}
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: {{ .Values.command | toJson}}
    # args: {{ .Values.args | toJson}}
    resources:
{{- toYaml .Values.resources | nindent 6 }}
  restartPolicy: Always
