# ProviderConfig for Work1 Account
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: work1-account
spec:
  credentials:
    source: PodIdentity
  assumeRoleChain:
    - roleARN: "arn:aws:iam::296062590485:role/superuser"

---

# ProviderConfig for Work2 Account
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: work2-account
spec:
  credentials:
    source: PodIdentity
  assumeRoleChain:
    - roleARN: "arn:aws:iam::195275675931:role/superuser"
